/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main.WorkSpaceProfiles;

import TheBusiness.Business.Business;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Bhagya
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form PerformanceReportsJPanel
     */
    JPanel workArea;
    Business business;
    ArrayList<Integer>arr1= new ArrayList();
    ArrayList<Integer>arr2= new ArrayList();
    ArrayList<String>arr3= new ArrayList();
    ArrayList<Integer>arr4= new ArrayList();
    ArrayList<Integer>arr5= new ArrayList();
    public PerformanceReportsJPanel(JPanel workArea, Business business, ArrayList<Integer>arr1,ArrayList<Integer>arr2,ArrayList<String>arr3,ArrayList<Integer>arr4,
    ArrayList<Integer>arr5) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.arr1 = arr1;
        this.arr2 = arr2;
        this.arr3 = arr3;
        this.arr4 = arr4;
        this.arr5 = arr5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
